//HintName: II.RegisterScoped`2.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

public static partial class RegistrationServiceCollectionExtensions
{
	static partial void RegisterScoped2(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.ReadOnlySpan<string> tags)
	{
		if (tags is [] || Intersects(tags, ["abc", "def"]))
		{
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Add(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Scoped(
				typeof(global::IService<string>),
				typeof(global::Service<string>)
			)
		);
		}

	}
}
