//HintName: II.RegisterSingleton`2.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

public static partial class RegistrationServiceCollectionExtensions
{
	static partial void RegisterSingleton2(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.ReadOnlySpan<string> tags)
	{
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Add(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(
				typeof(global::IService2<int>),
				typeof(global::Service<int>)
			)
		);

		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Add(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(
				typeof(global::IService2<string>),
				typeof(global::Service<string>)
			)
		);

	}
}
