//HintName: II.RegisterSingleton`1.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

public static partial class RegistrationServiceCollectionExtensions
{
	static partial void RegisterSingleton1(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.ReadOnlySpan<string> tags)
	{
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Replace(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(
				typeof(global::IService<string>),
				typeof(global::Service<string>)
			)
		);

	}
}
