//HintName: II.RegisterTransient`1.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

public static partial class RegistrationServiceCollectionExtensions
{
	static partial void RegisterTransient1(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.ReadOnlySpan<string> tags)
	{
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Transient(
				typeof(global::IService),
				typeof(global::Service)
			)
		);

	}
}
