//HintName: II.RegisterScoped`0.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

public static partial class RegistrationServiceCollectionExtensions
{
	static partial void RegisterScoped(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.ReadOnlySpan<string> tags)
	{
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Replace(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Scoped(
				typeof(global::Service<>),
				typeof(global::Service<>)
			)
		);
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Replace(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Scoped(
				typeof(global::IService<>),
				typeof(global::Service<>)
			)
		);

	}
}
