//HintName: II.RegisterTransient`0.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

public static partial class RegistrationServiceCollectionExtensions
{
	static partial void RegisterTransient(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.ReadOnlySpan<string> tags)
	{
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Add(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.KeyedTransient(
				typeof(global::Service),
				"Key",
				typeof(global::Service)
			)
		);
		global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.Add(
			services,
			global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.KeyedTransient(
				typeof(global::IService),
				"Key",
				typeof(global::Service)
			)
		);

	}
}
