//HintName: II.ServiceCollectionExtensions.g.cs
// <auto-generated />
#nullable enable

#pragma warning disable CS1591

public static partial class RegistrationServiceCollectionExtensions
{
	public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddTestsServices(
		this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
		params string[] tags
	)
	{
		services.RegisterScoped(tags);
		services.RegisterScoped1(tags);
		services.RegisterScoped2(tags);

		services.RegisterSingleton(tags);
		services.RegisterSingleton1(tags);
		services.RegisterSingleton2(tags);

		services.RegisterTransient(tags);
		services.RegisterTransient1(tags);
		services.RegisterTransient2(tags);

		services.RegisterServices(tags);
		
		return services;
	}

	static partial void RegisterScoped(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.ReadOnlySpan<string> tags);
	static partial void RegisterScoped1(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.ReadOnlySpan<string> tags);
	static partial void RegisterScoped2(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.ReadOnlySpan<string> tags);

	static partial void RegisterSingleton(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.ReadOnlySpan<string> tags);
	static partial void RegisterSingleton1(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.ReadOnlySpan<string> tags);
	static partial void RegisterSingleton2(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.ReadOnlySpan<string> tags);

	static partial void RegisterTransient(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.ReadOnlySpan<string> tags);
	static partial void RegisterTransient1(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.ReadOnlySpan<string> tags);
	static partial void RegisterTransient2(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.ReadOnlySpan<string> tags);

	static partial void RegisterServices(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.ReadOnlySpan<string> tags);
}
